backend:
  name: github
  repo: bogongroverchalet/website # Path to your Github repository
  branch: master # Branch to update (master by default)

media_folder: "img/uploads" # Folder where user uploaded files should go

publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "snippets" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Snippet" # Used in the UI, ie.: "New Post"
    folder: "_includes"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "hidden"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "page"
    label: "Page"
    files:
      - name: "homepage"
        label: "Homepage"
        file: "index.html"
        fields:
          - {label: "Body", name: "body", widget: "text"}
  - name: "layout"
    label: "Layout"
    editor:
      preview: false
    files:
      - name: "default"
        label: "Default"
        file: "_layouts/default.html"
        fields:
          - {label: "Body", name: "body", widget: "text"}
  - name: "testimonials"
    label: "Testimonial"
    folder: "_posts/testimonials"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Category", name: "category", widget: "hidden", default: "testimonials"}
