backend:
  name: git-gateway

media_folder: uploads # Folder where user uploaded files should go

publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "articles" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Article" # Used in the UI, ie.: "New Post"
    folder: "_articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Date", name: "date", widget: "hidden", default: "2017-8-8"}
      - {label: "List order", name: "list_order", widget: "hidden", required: false}
  - name: "snippets" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Snippet" # Used in the UI, ie.: "New Post"
    folder: "_includes"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "page"
    label: "Page"
    files:
      - name: "homepage"
        label: "Homepage"
        file: "index.html"
        fields:
          - label: "Summer tab"
            name: "summer_tabs"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Tab's slug", name: "href", widget: "string"}
          - label: "Winter tab"
            name: "winter_tabs"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Tab's slug", name: "href", widget: "string"}
          - {label: "Body", name: "body", widget: "text"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
  - name: "layout"
    label: "Layout"
    editor:
      preview: false
    files:
      - name: "default"
        label: "Default"
        file: "_layouts/default.html"
        fields:
          - {label: "Body", name: "body", widget: "text"}
  - name: "testimonials"
    label: "Testimonial"
    folder: "_posts/testimonials"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Order", name: "order", widget: "number", step: 1, min: 0, valueType: "int"}
      - {label: "Category", name: "category", widget: "hidden", default: "testimonials"}
  - name: "news"
    label: "News"
    folder: "_posts/news"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Expiry", name: "expires", widget: "date", default: "", required: false}
      - {label: "Publish date", name: "date", widget: "date"}
      - {label: "Category", name: "category", widget: "hidden", default: "news"}
      - {label: "Body", name: "body", widget: "markdown"}
        #- {label: "Order", name: "order", widget: "number", step: 1, min: 0, valueType: "int"}
